### PR TITLE
New entry password group can be renamed

### PR DESCRIPTION
**Pull request by uwekoegel**
use uuid as identifier for the password group

### CODE REVIEW

**Comment by smorks** [comment]
i believe this will create 2 "New Entry" password groups if they still have the old one, is that correct?

**Comment by uwekoegel** [comment]
Thats correct, but it would be possible to migrate the groups by copy all entries and groups of the old group into the new group and then delete the old group.
But I think a manual migration with a button in the settings is better than an automatic migration.

**Comment by uwekoegel** [comment]
Another solution to this issue would be to remember the UUID in the "Settings"-Entry and add a possibility to select the "New Entry"-Group

**Comment by smorks** [comment]
i agree that a manual migration would be better. i'll merge this as is, thanks!

**Pull request merged**
