### PR TITLE
[WIP]: Implement TOTP

### PR DESCRIPTION
**Pull request by Elbandi**
There is a totp support require the  KeeOtp plugin installed. But this plugin is removed from download list, and source repo is missing too.

I implement a better totp support, and added get-totp calls too. (KeePassXC-Browser require 2.6.1 reported version, so we sould update too)

Some code come from here: https://github.com/KeeTrayTOTP/KeeTrayTOTP, but both project license is GPL3, so it's not a problem.

This is a WIP, any suggestion are welcome.

### CODE REVIEW

**Comment by smorks** [comment]
wow this looks great, thanks! i'll try and review this soon when i have some free time!

**Comment by exileed** [comment]
> 
> 
> wow this looks great, thanks! i'll try and review this soon when i have some free time!

up

**Comment by smorks** [comment]
i'm not sure if this is necessary anymore, since KeePass has built-in OTP support (https://keepass.info/help/base/placeholders.html#otp) since version 2.47. i just need to add support in this plugin to use it.

**Comment by smorks** [comment]
new totp support added here: bc73b6b8b269565029fb222a11fb462a31256a57, with some changes taken from PR. thanks!

**Pull request closed without merging**
